# Generated by Django 5.2 on 2025-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_rename_created_at_marketplace_stored_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='image',
            field=models.ImageField(default=2, upload_to='marketplace_images/'),
            preserve_default=False,
        ),
    ]
